version: "3"
services:
  twintdocker:
    image: twintdocker
    ports:
      - "8080:8080"
    networks:
      - twint-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    container_name: mysqldb
    networks:
      - twint-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - M
    ports:
      - "3306:3306"
    restart: always

  customerservice: #it is just a name, which will be used only in this file.
    image: twintdocker               #name of the image after dockerfile executes
    container_name: twintdockerapp  #name of the container created from docker image
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "8082:8082"                       #docker containter port with your os port
    restart: always

    depends_on: #define dependencies of this app
      - db                                #dependency name (which is defined with this name 'db' in this file earlier)
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/property?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

networks:
  twint-mysql:


